POST http://localhost:3000/api/questions
Content-Type: application/json

{
  "question": "Formulae to calculate speed?",
  "options": ["displacement/time", "time/distance", "distance/time", "time/displacement"],
  "correct_answer": "distance/time",
  "points": 5,
  "quiz_id": "65ff1b62bc89d9cabbc90ec8"
}

###

GET http://localhost:3000/api/questions

###

GET http://localhost:3000/api/question/65fad4d728e3e26c36449b7f

###

PATCH http://localhost:3000/api/question/65fad4d728e3e26c36449b7f
Content-Type: application/json

{
  "question": "What is 5 * 8?",
  "options": [58, 85, 40, 22],
  "correct_answer": 40,
  "points": 10
}

###

DELETE http://localhost:3000/api/question/65ff1fb49fabefe227ee10ca
Content-Type: application/json

{
  "quizId": "65ff1b62bc89d9cabbc90ec8"
}