POST http://localhost:3000/api/questions/65ff7351241c70e017738184
Content-Type: application/json

{
  "question": "RBC stands for?",
  "options": [1, 2, 3, 4],
  "correct_answer": 1,
  "points": 5
}

###

GET http://localhost:3000/api/questions

###

GET http://localhost:3000/api/questions/65fad4d728e3e26c36449b7f

###

PATCH http://localhost:3000/api/questions/65fad4d728e3e26c36449b7f
Content-Type: application/json

{
  "question": "What is 5 * 8?",
  "options": [58, 85, 40, 22],
  "correct_answer": 40,
  "points": 10
}

###

DELETE http://localhost:3000/api/questions/65ff70c7e8440601d15e8093
Content-Type: application/json

{
  "quizId": "65ff64f8f400d3ec8e5ff835"
}