POST http://localhost:3000/api/questions/66018111db3aa87df5037bd5
Content-Type: application/json

{
  "question": "Which is not a hardware?",
  "options": ["Monitor", "MS Excel", "Mouse", "Speaker"],
  "correct_answer": "MS Excel",
  "points": 5
}

###

GET http://localhost:3000/api/questions

###

GET http://localhost:3000/api/questions/65ff76cadba1c8b88db68262

###

PATCH http://localhost:3000/api/questions/66018229db3aa87df5037bdb
Content-Type: application/json

{
  "question": "Which is not a hardware component?",
  "options": ["Monitor", "MS Excel", "Mouse", "Speaker"],
  "correct_answer": "MS Excel",
  "points": 5
}

###

DELETE http://localhost:3000/api/questions/65ff70c7e8440601d15e8093
Content-Type: application/json

{
  "quizId": "65ff64f8f400d3ec8e5ff835"
}