POST http://localhost:3000/api/quiz/65ffa772f60a390514dad503
Content-Type: application/json

{
  "name": "Computer Quiz",
  "questions": [],
  "highest_score": 0
}

###

GET http://localhost:3000/api/quizzes

###

GET http://localhost:3000/api/quiz/65ff7351241c70e017738184

###

PATCH http://localhost:3000/api/quiz/6600f77176880aba656a8750
Content-Type: application/json

{
  "name": "Maths Quiz",
  "highest_score": 0
}

###

DELETE http://localhost:3000/api/quiz/65ff64f8f400d3ec8e5ff835
Content-Type: application/json

{
  "userId": "65ff6397f400d3ec8e5ff82d"
}