POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "alex123"
}

###

POST http://localhost:3000/api/decode
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWZmNjM5N2Y0MDBkM2VjOGU1ZmY4MmQiLCJ1c2VyTmFtZSI6IkFsZXgiLCJlbWFpbCI6ImFsZXhAZ21haWwuY29tIiwiaWF0IjoxNzExMjc4NTExfQ.2HxoEig_dtN1z7_W23PdHS9rpcHQzwfELHwrlxo1kJo"
}

###

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "userName": "John",
  "email": "john@gmail.com",
  "password": "john123"
}

###

GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/getUser/65ff6397f400d3ec8e5ff82d

###

DELETE http://localhost:3000/api/user